# Generated by Django 5.1.3 on 2024-12-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='students', to='parent.parent'),
        ),
    ]
